### ISSUE TITLE
Install procedure doesn't work.

### ISSUE THREAD

**Issue by drysdam** [colah/ImplicitCAD#115]
Debian 7 64-bit here. Followed instructions in FAQ (sudo apt-get install ghc cabal-install; cabal update && cabal install implicit) and got:

extopenscad.hs:26:149:
    Module `Options.Applicative' does not export `reader'

extopenscad.hs:26:169:
    Module `Options.Applicative' does not export `(&)'
cabal: Error: some packages failed to install:
implicit-0.0.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by mmachenry** [comment]
These should be fixed now. Could someone verify that this issue has been resolved? I have no problems building the project now. I will close this issue eventually if I don't hear back.

**Comment by firegurafiku** [comment]
Unfortunately, on my system (Fedora 21, GHC 7.6.3) installation still fails:
```text
$ cabl install implicit
Resolving dependencies...
Downloading implicit-0.0.4...
Configuring implicit-0.0.4...
Building implicit-0.0.4...
Preprocessing library implicit-0.0.4...
(.....)
Graphics/Implicit/ExtOpenScad/Primitives.hs:429:23:
    Overlapping instances for OTypeMirror String
      arising from a use of `argument'
    Matching instances:
      instance OTypeMirror String
        -- Defined at Graphics/Implicit/ExtOpenScad/Util/OVal.hs:34:30
      instance OTypeMirror a => OTypeMirror [a]
        -- Defined at Graphics/Implicit/ExtOpenScad/Util/OVal.hs:44:31
    In the first argument of `doc', namely `argument "unit"'
    In a stmt of a 'do' block:
      unit :: String <- argument "unit"
                        `doc` "the unit you wish to work in"
    In the expression:
      do { example "unit(\"inch\") {..}";
           unit :: String <- argument "unit"
                             `doc` "the unit you wish to work in";
           let mmRatio "inch" = Just 25.4
               mmRatio "in" = mmRatio "inch"
               mmRatio "foot" = Just 304.8
               mmRatio "ft" = mmRatio "foot"
               mmRatio "yard" = Just 914.4
               mmRatio "yd" = mmRatio "yard"
               mmRatio "mm" = Just 1
               mmRatio "cm" = Just 10
               mmRatio "dm" = Just 100
               mmRatio "m" = Just 1000
               mmRatio "km" = Just 1000000
               mmRatio "\181m" = Just 0.001
               mmRatio "um" = mmRatio "\181m"
               mmRatio "nm" = Just 0.0000001
               mmRatio _ = Nothing;
           return
           $ case mmRatio unit of {
               Nothing -> do { ... }
               Just r
                 -> return
                    $ objMap (Prim.scale (r, r)) (Prim.scale (r, r, r)) children } }
Failed to install implicit-0.0.4
cabal: Error: some packages failed to install:
implicit-0.0.4 failed during the building phase. The exception was:
ExitFailure 1

```

**Comment by mmachenry** [comment]
I have merged a pull request addressing GHC-7.6.3 backward compatibility. Can you please try again?

**Comment by firegurafiku** [comment]
@mmachenry 

Yeah, now it builds. I cannot test it at the moment, but it runs:
```text
$ dist/build/extopenscad/extopenscad
Usage: extopenscad [-o|--output FILE] [-f|--format FORMAT] [-r|--resolution RES]
                   [--xml-error] FILE
  Extended OpenSCAD

```

**Comment by mmachenry** [comment]
Great, thanks for your help. I'm going to close this issue. Feel free to file any more in the future or reopen this if you have another problem.
